name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: 'choice'
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
env:
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: NPM Setup
        run: |
          npm set registry "https://registry.npmjs.org/"
          npm set //registry.npmjs.org/:_authToken $NPM_ACCESS_TOKEN
          npm whoami

      - name: Git Setup
        run: |
          git config --global user.email "wpbrock@gmail.com"
          git config --global user.name "Test Reporter Service Release Bot"

      - name: Install Dependencies
        run: npm ci

      - run: npm run release -- ${{ github.event.inputs.release_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
